### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by PsyMar**
stading should be standing

### CODE REVIEW

**Comment by Feneric** [comment]
Thanks. Please fix it in the relevant output files, too, so that the tests will still pass. I'll happily merge it when the tests pass.

**Comment by PsyMar** [comment]
There, that should work.  Got a bit confused as to what I was doing, so you might want to squash all those commits into one.

**Comment by PsyMar** [comment]
Also, thanks for this great project!  I've been converting over my unfinished projects to use this.

**Comment by Feneric** [comment]
You're welcome. Glad it helps.

**Pull request merged**
