### PR TITLE
add overwrite of visit_Constant to workaround problems with Python 3.8

### PR DESCRIPTION
**Pull request by svigerske**
See Feneric/doxypypy#70.

I don't know whether `visit_Constant` should actually do something with the `containingNodes` argument that it would receive.

### CODE REVIEW

**Comment by fer-rum** [comment]
I would expect it to produce some output in the generated HTML telling me that the visited node is a constant…

But I have no clue whether this is the correct point to add it.

Doxypypy no longer failing when it encounters such nodes is already a good step forward.

**Comment by burgerbecky** [comment]
It would be great if this pull request for visit_Constant was merged and doxypypy updated on PyPi because this patch works on Python 3.9 and I'd rather not have to manually patch doxypypy to get my builds to work

**Comment by forthommel** [comment]
Any news about the merging of this PR onto the mainline?

**Comment by guidfort** [comment]
Fix is in master, when comes a pypi version (0.8.8.7)

**Pull request merged**
