### PR TITLE
Remove 'object' from inherited class list

### PR DESCRIPTION
**Pull request by Alcolo47**
In the class hierarchy, I don't care that a class inherits from object (because it always does).

This pull request also simplfy the graphical class hierachy and harmonize old-style class and new-style class representation.

Merge it if you want, it's not essantial.

Note:
bool([]) == false, then {}.get("x", []) or [] return always the second list.

Note2:
I don't know why but "detect" return me None sometimes ... I didn't dig it deeper.

### CODE REVIEW

**Comment by Feneric** [comment]
It's a reasonable idea and I can see it being useful to quite a few people. I can also see an argument for why some might want to see old and new classes separated. Could you make it a command line option? I'll happily merge it if it is made optional (I don't mind it being the default behavior; I suspect most will be happy to remove the generic object reference).

**Comment by Alcolo47** [comment]
OK I'll make a new pull request

**Comment by Alcolo47** [comment]
oups

**Comment by timsnyder** [comment]
@Feneric and @Alcolo47 Do the tests pass for you after this PR?  I get test errors about `object_respect` not being in the `Options` object passed into the tests.  If I revert d278b740215f2e3625f9092f62fcfc595adf692e and d3d5a18c7a944ec42da403b58099f805548ba9af, they pass again.

If the tests are failing for you guys, I can try to put together a PR to make them pass again.  If they aren't failing for you, I'm curious what I'm doing wrong.

@Feneric, do you have interest in setting up CI on Travis or elsewhere?  I could create a Travis yml and submit a PR if you are.

**Comment by Feneric** [comment]
I thought they had, but it's been awhile since I've personally run them. There's a small fix I've been looking to merge, but real-world stuff keeps getting in the way.

I'd love to modernize testing for doxypypy. I was looking into just getting it to run multiple Python versions more cleanly using tox, but getting CI working would be sweet. I'd gladly merge any change that helps clean up doxypypy testing.

**Pull request merged**
